language: go

go:
  - 1.9.2

install:
  - go get -u github.com/golang/dep/...

script:
  - $GOPATH/bin/dep ensure -v
  - go test -v ./...

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
